# Release build script
#
# Uses the common build logic, but also gains capabilities related to releasing the product.

# Only trigger manually

trigger: none

pr: none

variables:
  - group: ai-agent-evals-ado-extension-release

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      skipBuildTagsForGitHubPullRequests: true
    # featureFlags:
    # autoBaseline: false
    sdl:
      baseline:
        baselineSet: default
        baselineFile: $(Build.SourcesDirectory)/.gdn/.gdnbaselines
      sourceAnalysisPool:
        name: 1es-pool001
        image: 1es-managed-image-001
        os: windows
    pool:
      name: 1es-pool001
      image: 1es-managed-image-001
      os: windows

    stages:
      - stage: stage
        jobs:
          - job: job
            templateContext:
              outputs:
                - output: pipelineArtifact
                  path: $(Build.SourcesDirectory)/out/prod
                  artifact: drop

                - output: adoExtension
                  targetPath: $(Build.SourcesDirectory)/out/prod
                  connectedServiceNameAzureRM: "esrp-codesign-service-connection"
                  fileType: vsix
                  vsixFile: $(Build.SourcesDirectory)/out/prod/*.vsix
                  useV5: true
            steps:
              - template: .azure-devops/common-steps.yml@self
