name: Single AI Agent Evaluation

env:
  data-path: "${{ github.workspace }}/data/dataset.json"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  evaluate:
    name: AI Agent Evaluation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run evaluation
        uses: microsoft/ai-agent-eval@v1-beta
        with:
          azure-ai-project-endpoint: ${{ secrets.AZURE_AI_PROJECT_ENDPOINT }}
          deployment-name: ${{ secrets.DEPLOYMENT_NAME }}
          data-path: ${{ env.data-path }}
          agent-ids: ${{ secrets.AGENT_ID }}